# Generated by Django 6.0.1 on 2026-01-12 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_payment_invoice_payment_purchase_invoice_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendorPayment',
        ),
    ]
