# Generated by Django 6.0.1 on 2026-01-12 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_delete_vendorpayment'),
        ('purchases', '0002_alter_purchase_balance_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='purchase_invoice',
        ),
        migrations.AddField(
            model_name='payment',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchases.purchase'),
        ),
    ]
