# Generated by Django 5.2.8 on 2026-02-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_remove_purchaseinvoiceitem_invoice_and_more'),
        ('payments', '0006_alter_payment_id'),
        ('purchases', '0003_purchase_payment_status_alter_purchase_id_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('sales_invoice__isnull', False), ('purchase__isnull', True)), models.Q(('sales_invoice__isnull', True), ('purchase__isnull', False)), _connector='OR'), name='payment_must_link_to_one_document'),
        ),
    ]
