# Generated by Django 6.0.1 on 2026-01-07 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='stockmovement',
            old_name='reference_id',
            new_name='reference',
        ),
    ]
